tasks:
  - init: > 
      python3 -m pip install -r requirements.txt
    command: >
      export FLASK_APP=app.py &&
      export FLASK_ENV=development &&
      python3 -m flask run
ports:
  - port: 5000
    onOpen: open-browser
